apiVersion: v1
kind: Service
metadata:
  name: opsmind-app-service
  namespace: opsmind
  labels:
    app: opsmind-app
spec:
  type: NodePort
  selector:
    app: opsmind-app
  ports:
    - name: http-metrics
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080